# Keywords
KW_START = 'START' 
KW_STOP = 'STOP'   #
KW_VAR = 'VAR'  #
KW_AS = 'AS' #
KW_INT = 'INTEGER' 
KW_FLOAT = 'FLOAT' #
KW_STRING = 'STRING' #
KW_BOOLEAN = 'BOOL' #
KW_OUTPUT = 'OUT' #

# LANGUAGE SPECIFICS
NEWLINE = 'NL'  # Value is (#)
CONCATENATOR = 'CON'  # Value is (&)
COMMENT_INIT = 'COMI'  # Value is (*)
ESCAPE_OPEN = 'ESCO'  # Value is ([)
ESCAPE_CLOSE = 'ESCC'  # VALUE IS (])

# VALUES
STRING = 'STR'
CHAR = 'CH'
INT = 'INT'
FLOAT = 'FLOAT'
BOOL_TRUE = 'TRUE'
BOOL_FALSE = 'FALSE'

# ASSIGNMENT OPERATOR
EQUALS = 'EQUAL'

# IDENTIFIER
IDENTIFIER = 'IDEN'

# MATH OPERATORS
MULTIPLY = 'MUL'
DIVIDE = 'DIV'
PLUS = 'ADD'
MINUS = 'SUB'
MODULO = 'MODULO'

# LOGICAL OPERATORS
AND = 'AND'
OR = 'OR'
NOT = 'NOT'
GREATER_THAN = 'GRE'
GREATER_OR_EQUAL = 'GOE'
LESS_THAN = 'LES'
LESS_OR_EQUAL = 'LOE'
LOGIC_EQUAL = 'LE'
NOT_EQUAL = 'NE'

# SPECIAL CHARACTERS
COMMA = 'COM'

# GROUPING SYMBOLS
PAREN_OPEN = 'PO'
PAREN_CLOSE = 'PC'

# ERROR
ERROR = 'ERR'
