
# Keywords
KW_START = 'KW_START'
KW_STOP = 'KW_STOP'
KW_VAR = 'KW_VAR'
KW_AS = 'KW_AS'
KW_INT = 'KW_INTEGER'
KW_FLOAT = 'KW_FLOATING'
KW_STRING = 'KW_STRING'
KW_BOOLEAN = 'KW_BOOLEAN'
KW_OUTPUT = 'KW_OUTPUT'
KW_INPUT = 'KW_INPUT'
KW_CHAR = 'KW_CHAR'

# LANGUAGE SPECIFICS
NEWLINE = 'NL'  # Value is (#)
CONCATENATOR = 'CON'  # Value is (&)
COMMENT_INIT = 'COMI'  # Value is (*)
ESCAPE_OPEN = 'ESCO'  # Value is ([)
ESCAPE_CLOSE = 'ESCC'  # VALUE IS (])

# VALUES
STRING = 'V_STR'
CHAR = 'V_CH'
INT = 'V_INT'
FLOAT = 'V_FLOAT'
BOOL = 'V_BOOL'
BOOL_TRUE = 'V_TRUE'
BOOL_FALSE = 'V_FALSE'

# ASSIGNMENT OPERATOR
EQUALS = 'EQUAL'

# IDENTIFIER
IDENTIFIER = 'IDEN'

# MATH OPERATORS
MULTIPLY = 'MUL'
DIVIDE = 'DIV'
PLUS = 'ADD'
MINUS = 'SUB'
MODULO = 'MODULO'

# LOGICAL OPERATORS
AND = 'AND'
OR = 'OR'
NOT = 'NOT'
GREATER_THAN = 'GRE'
GREATER_OR_EQUAL = 'GOE'
LESS_THAN = 'LES'
LESS_OR_EQUAL = 'LOE'
LOGIC_EQUAL = 'LE'
NOT_EQUAL = 'NE'

# SPECIAL CHARACTERS
COMMA = 'COMMA'
COLON = 'COLN'


# GROUPING SYMBOLS
PAREN_OPEN = 'PO'
PAREN_CLOSE = 'PC'

# ERROR
ERROR = 'ERR'

# STATEMENT TYPE
ST_DECLARATION = 'DECLARATION'
ST_ASSIGNMENT_STRING = 'ASSIGNMENT_STR'
ST_ASSIGNMENT_MATH = 'ASSIGNMENT_MATH'
ST_ASSIGNMENT_LOGIC = 'ASSIGNMENT_BOOL'
ST_OUTPUT = 'ST_OUTPUT'
ST_INPUT = 'ST_INPUT'
